FROM golang:1-alpine as builder
RUN apk --no-cache add git gcc libc-dev linux-headers
WORKDIR /go/src/ghost
COPY . .
RUN    export CGO_ENABLED=1 \
    && mkdir dist \
    && go mod download \
    && go build -o dist/ghost ./cmd/ghost

FROM golang:1-alpine
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /go/src/ghost/dist/ /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/ghost"]
