FROM golang:1-alpine as builder
RUN apk --no-cache add git
WORKDIR /go/src/gofer
COPY . .
RUN    export CGO_ENABLED=0 \
    && mkdir dist \
    && go mod download \
    && go build -o dist/gofer ./cmd/gofer

FROM golang:1-alpine
RUN apk --no-cache add ca-certificates 
WORKDIR /root
COPY --from=builder /go/src/gofer/dist/ /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/gofer"]
