FROM golang:1-alpine as builder
RUN apk --no-cache add git
WORKDIR /go/src/serf
RUN    export CGO_ENABLED=0 \
    && git clone https://github.com/hashicorp/serf.git . \
    && mkdir dist \
    && git checkout v0.9.5 \
    && go build -o dist ./cmd/serf/...

FROM golang:1-alpine
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /go/src/serf/dist/ /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/serf"]
