version: "3.8"
services:

  gofer:
    build:
      context: "."
      dockerfile: "Dockerfile-gofer"
    volumes:
      - "./gofer.json:/root/gofer.json"

  ghost:
    build:
      context: "."
      dockerfile: "Dockerfile-ghost"
    volumes:
      - "./gofer.json:/root/gofer.json"
      - "./ghost.json:/root/ghost.json"

  spectre:
    build:
      context: "."
      dockerfile: "Dockerfile-spectre"
    volumes:
      - "./spectre.json:/root/spectre.json"

  spire:
    build:
      context: "."
      dockerfile: "Dockerfile-spire"
    volumes:
      - "./spire.json:/root/spire.json"
